dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_script:
  - python3 ./_local_config_generator.py

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - cat ./backend/local_config.py